version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - pwd
      - pip install --upgrade awscli boto3

  pre_build:
    commands:
      - export S3_BASE_PATH=atlantis
      - export DRYRUN=""
      #- export DRYRUN="--dryrun"

      - echo $HOST_BUCKET/$S3_BASE_PATH
      - echo $DRYRUN

  build:
    commands:

  post_build:
    commands:
      - pwd

      # We use versioning on the buckets so that we can specify a specific version of the template to use
      # Therefore, so we do not create extra versions, we will use only copy changed files.

      # Copy template files to host bucket
      - echo "Executing script to sync templates..."
      - chmod +x ./scripts/sync_templates.sh
      - ./scripts/sync_templates.sh $HOST_BUCKET $S3_BASE_PATH/templates templates $DRYRUN

      # Inventory host bucket
      - echo "Executing script to inventory S3..."
      - chmod +x ./scripts/s3_inventory.py
      - ./scripts/s3_inventory.py $HOST_BUCKET $S3_BASE_PATH --output-dir outputs
      - [ -z "$DRYRUN" ] && aws s3 cp ./outputs/inventory.json s3://$HOST_BUCKET/$S3_BASE_PATH || echo "[DRYRUN] Would copy ./outputs/inventory.json to s3://$HOST_BUCKET/$S3_BASE_PATH"

      # Send sharable scripts to host bucket
      - echo "Executing script to upload scripts..."
      - chmod +x ./scripts/upload_scripts.sh
      - ./scripts/upload_scripts.sh $HOST_BUCKET $S3_BASE_PATH/utilities scripts $DRYRUN

artifacts:
  files:
    - '**/*'