version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - pwd
      - pip install --upgrade awscli boto3

  pre_build:
    commands:
      - export S3_BASE_PATH=atlantis
      - export DRY_RUN="--dryrun"

      - echo $HOST_BUCKET/$S3_BASE_PATH
      - echo $DRY_RUN

  build:
    commands:

  post_build:
    commands:
      - pwd

      # We use versioning on the buckets so that we can specify a specific version of the template to use
      # Therefore, so we do not create extra versions, we will use only copy changed files.

      # Copy template files to host bucket
      - echo "Copying templates to s3..."
      - aws s3 sync ./templates "s3://$HOST_BUCKET/$S3_BASE_PATH/templates" --delete --exact-timestamps --size-only --exclude "*" --exclude ".*" --exclude ".*/*" --include "*.zip" --include "*.json" --include "*.yaml" --include "*.yml" $DRY_RUN
      - echo "Template copy complete."

      # Inventory host bucket
      - chmod +x ./scripts/s3_inventory.py
      - ./scripts/s3_inventory.py $HOST_BUCKET $S3_BASE_PATH --output-dir outputs
      - echo "Inventory complete."
      - aws s3 cp ./outputs/inventory.json s3://$HOST_BUCKET/$S3_BASE_PATH
      - echo "Inventory file copied to s3 bucket root $HOST_BUCKET/$S3_BASE_PATH"

      # Send sharable scripts to host bucket
      - chmod +x ./scripts/upload_scripts.sh
      - ./scripts/upload_scripts.sh $HOST_BUCKET $S3_BASE_PATH/utilities scripts
      - echo "Scripts uploaded to s3 bucket $HOST_BUCKET/$S3_BASE_PATH/utilities"

artifacts:
  files:
    - '**/*'