AWSTemplateFormatVersion: '2010-09-09'
Description: 'API Gateway CloudWatch Logs Role and Account Configuration'

# -- In order to push API Gateway Logs to CloudWatch, a role must be created at the 
# -- account level and then added to API Gateway.
# -- This template will add a service role to allow API Gateway to write to CloudWatch logs
# -- See https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-logging.html

Resources:
  # API Gateway CloudWatch Logs Role
  ApiGatewayCloudWatchLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  # Set API Gateway Account Configuration
  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchLogsRole.Arn
