AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "CloudFront distribution with S3 origin access control (OAC). Supports external invalidator services via S3 event notifications - Deployed using SAM"

# Atlantis for AWS SAM Deployments
# Storage Infrastructure Template
# Author: Chad Kluck - 63klabs.net
# Version: v0.1.0/2025-12-08

# Documentation, Issues/Feature Requests, Latest Updates, and Security Reports on GitHub:
# https://github.com/63klabs/atlantis-cfn-template-repo-for-serverless-deployments/


# =============================================================================
# META DATA
# -----------------------------------------------------------------------------
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-interface.html
# 

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label:
          default: "Resource Naming"
        Parameters:
          - Prefix
          - ProjectId
          - S3BucketNameOrgPrefix
          - RolePath
      -
        Label:
          default: "External Resources and Alarm Notifications"
        Parameters:
          - AlarmNotificationEmail
          - PermissionsBoundaryArn
          - S3LogBucketName
          - InvalidatorArn

# =============================================================================
# PARAMETERS
# -----------------------------------------------------------------------------
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
#

Parameters:

  # ---------------------------------------------------------------------------
  # Application Resource Naming

  Prefix:
    Type: String
    Description: "Prefix pre-pended to all resources. This can be thought of as a Name Space used to identify ownership/access for teams, departments, etc. For example, resources named ws-* could belong to the web service team and could have IAM permissions to allow access to other ws-* resources. The Prefix must have a corresponding CloudFormation Service Role. Short, descriptive 2-6 character values work best. Due to resource naming length restrictions, length of Prefix + Project ID should not exceed 28 characters. Resources are named <Prefix>-<ProjectId>-<StageId>-<ResourceId>"
    Default: "acme" 
    AllowedPattern: "^[a-z][a-z0-9-]{0,6}[a-z0-9]$"
    MinLength: 2
    MaxLength: 8
    ConstraintDescription: "2 to 8 characters. Lower case alphanumeric and dashes. Must start with a letter and end with a letter or number. Length of Prefix + Project ID should not exceed 28 characters."

  ProjectId:
    Type: String
    Description: "This is the Project or Application Identifier. If you receive 'S3 bucket name too long' errors during stack creation, then you must shorten the Project ID or use an S3 Org Prefix. Due to resource naming length restrictions, length of Prefix + Project ID should not exceed 28 characters. Resources are named <Prefix>-<ProjectId>-<StageId>-<ResourceId>"
    AllowedPattern: "^[a-z][a-z0-9-]{0,24}[a-z0-9]$"
    MinLength: 2
    MaxLength: 26
    ConstraintDescription: "Minimum of 2 characters (suggested maximum of 20). Lower case alphanumeric and dashes. Must start with a letter and end with a letter or number. Length of Prefix + Project ID should not exceed 28 characters."

  S3BucketNameOrgPrefix:
    Type: String
    Description: "By default, to enforce uniqueness, buckets include account and region in the bucket name. However, due to character limits, you can specify your own S3 prefix (like an org code). This will be used in addition to the Prefix entered above. Note that this length is shared with the recommended length of 20 characters for Resource Identifiers. So if you have a 10 character S3BucketNameOrgPrefix, you are limited to 10 characters for your bucket name identifier in your templates. Buckets are named <Prefix>-<Region>-<AccountId>-<ProjectId>-<StageId>-<ResourceId> or <S3OrgPrefix>-<Prefix>-<ProjectId>-<StageId>-<ResourceId>"
    Default: ""
    AllowedPattern: "^[a-z0-9][a-z0-9-]{0,18}[a-z0-9]$|^$"
    ConstraintDescription: "May be empty or 2 to 20 characters (8 or less recommended). Lower case alphanumeric and dashes. Must start and end with a letter or number."

  RolePath:
    Type: String
    Description: "Path to use for IAM Roles and Policies. You may wish to separate out your applications from users, or create seperate paths per prefix or application. Specific paths may required by permission boundaries. Ex: /ws-hello-world-test/ or /app_role/"
    Default: "/"
    AllowedPattern: "^\\/([a-zA-Z0-9-_]+[\\/])+$|^\\/$"
    ConstraintDescription: "May only contain alphanumeric characters, forward slashes, underscores, and dashes. Must begin and end with a slash."

  # ---------------------------------------------------------------------------
  # Deployment Environment

  # DeployRole:
  #   Type: String
  #   Description: "IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions"

  # ---------------------------------------------------------------------------
  # External Resources and Alarm Notifications

  AlarmNotificationEmail:
    Type: String
    Description: "Email address to send notifications to when alarms are triggered. Be sure to check the inbox as you will need to confirm the subscription."
    AllowedPattern: "^[\\w\\-\\.]+@([\\w\\-]+\\.)+[\\w\\-]{2,4}$"
    ConstraintDescription: "A valid email address"

  PermissionsBoundaryArn:
    Type: String
    Description: "Permissions Boundary is a policy attached to a role to further restrict the permissions of the role. Your organization may or may not require boundaries. If left empty, no permissions boundary will be used."
    Default: ""
    AllowedPattern: "^$|^arn:aws:iam::\\d{12}:policy\\/[\\w+=,.@\\-\\/]*[\\w+=,.@\\-]+$"
    ConstraintDescription: "Must be empty or a valid IAM Policy ARN in the format: arn:aws:iam::{account_id}:policy/{policy_name}"

  S3LogBucketName:
    Type: String
    Description: "The name of the S3 bucket used for logging. This is a required parameter for the S3 bucket."
    Default: ""
    AllowedPattern: "^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$|^$"
    ConstraintDescription: "Must be a valid S3 bucket name or empty. Must be between 3 and 63 characters long. Lower case alphanumeric and dashes. Must start and end with a letter or number."

  InvalidatorArn:
    Type: String
    Description: "ARN of the Lambda function providing your invalidator service for CloudFront distributions."
    Default: ""
    AllowedPattern: "^$|^arn:aws:lambda:[a-z0-9-]+:\\d{12}:function:[a-zA-Z0-9-_]+$"
    ConstraintDescription: "Must be empty or a valid ARN for Lambda"

# =============================================================================
# CONDITIONS
# -----------------------------------------------------------------------------
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html
#

Conditions:
  UseS3BucketNameOrgPrefix: !Not [!Equals [!Ref S3BucketNameOrgPrefix, ""]]
  # HasPermissionsBoundaryArn: !Not [!Equals [!Ref PermissionsBoundaryArn, ""]]
  HasLoggingBucket: !Not [!Equals [!Ref S3LogBucketName, ""]]
  HasInvalidatorArn: !Not [!Equals [!Ref InvalidatorArn, ""]]

# =============================================================================
# RESOURCES
# -----------------------------------------------------------------------------
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html  
#
Resources:
  
  # Creates a new S3 bucket with SSE and public access blocked.
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete # Set to Delete because if we delete the stack, we don't need the bucket - don't need to retain data
    Properties:
      BucketName: !Sub
        - "${OrgPrefix}${Prefix}-${ProjectId}-${AWS::Region}-${AWS::AccountId}"
        - OrgPrefix: !If [UseS3BucketNameOrgPrefix, !Sub "${S3BucketNameOrgPrefix}-", ""]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration: !If
      - HasLoggingBucket
      - DestinationBucketName: !Ref S3LogBucketName
        LogFilePrefix: !Sub
          - "${OrgPrefix}${Prefix}-${ProjectId}-${AWS::Region}-${AWS::AccountId}/"
          - OrgPrefix: !If [UseS3BucketNameOrgPrefix, !Sub "${S3BucketNameOrgPrefix}-", ""]
      - !Ref AWS::NoValue
      Tags: !If
        - HasInvalidatorArn
        - - Key: "AllowInvalidationEvents"
            Value: "true"
        - !Ref AWS::NoValue
      NotificationConfiguration: !If
        - HasInvalidatorArn
        - LambdaConfigurations:
            - Event: "s3:ObjectCreated:*"
              Function: !Ref InvalidatorArn
            - Event: "s3:ObjectRemoved:*"
              Function: !Ref InvalidatorArn
            - Event: "s3:LifecycleExpiration:*"
              Function: !Ref InvalidatorArn
        - !Ref AWS::NoValue

  # Creates a bucket policy giving OAC read-only access to the S3 bucket.
  # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:

          - Sid: "DenyNonSecureTransportAccess"
            Effect: Deny
            Principal: "*"
            Action: 's3:*'
            Resource:
              - !GetAtt Bucket.Arn
              - !Join [ '/', [ !GetAtt Bucket.Arn, '*' ] ]
            Condition:
              Bool:
                "aws:SecureTransport": false

          - Sid: AllowCloudFrontServicePrincipalReadOnly
            Action:
            - 's3:GetObject'
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Resource: !Sub "${Bucket.Arn}/*"
            Condition:
              StringLike:
                "aws:SourceArn": !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/*"

          - Sid: AllowCodeBuildReadWriteDelete
            Action:
            - 's3:GetObject'
            - 's3:PutObject'
            - 's3:DeleteObject'
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Resource: !Sub "${Bucket.Arn}/*"
            Condition:
              StringLike:
                "aws:SourceArn": !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${Prefix}-${ProjectId}-*"

  # Creates a Lambda permission to allow S3 to invoke the external invalidator function
  # This resource is only created when InvalidatorArn is provided
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html
  S3InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Condition: HasInvalidatorArn
    Properties:
      FunctionName: !Ref InvalidatorArn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !GetAtt Bucket.Arn

# =============================================================================
# OUTPUTS
# -----------------------------------------------------------------------------
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
#
# Place anything interesting that you would like to quickly refer to in 
# your cloudformation OUTPUT section. Test URLs, direct links to resources, etc
#

Outputs:

  BucketName:
    Description: The S3 Bucket Name used for CloudFront Origin.
    Value: !Ref Bucket

  OriginBucketDomainForCloudFront:
    Description: Domain to use for CloudFront S3 Origin.
    Value: !GetAtt Bucket.DomainName

  AllowedCloudFrontAndCodeBuild:
    Description: Access to bucket is restricted to CloudFront (Read) and CodeBuild (CRUD) with the following atlantis:Application tag value.
    Value: !Sub "${Prefix}-${ProjectId}"

  LoggingBucketName:
    Condition: HasLoggingBucket
    Description: The S3 Bucket Name used for logging.
    Value: !Ref S3LogBucketName

  InvalidatorArn:
    Condition: HasInvalidatorArn
    Description: ARN of the external invalidator service configured for S3 event notifications
    Value: !Ref InvalidatorArn

  InvalidationEventsEnabled:
    Description: Indicates whether S3 event notifications for cache invalidation are enabled
    Value: !If [HasInvalidatorArn, "true", "false"]
