name: Deploy to S3

# This script prepares templates and uploads to s3
# An IAM role must present to provide permissions 

# Set the following GitHub Actions secrets and variables for your repository:
# Secrets:
#   AWS_RELEASE_ACCT
#   AWS_RELEASE_REGION
# Variables:
#   AWS_RELEASE_BUCKET - bucket to upload artifact to
#   AWS_RELEASE_BUCKET_UTILS_PATH - Must be single / or begin and end with / (suggested: /atlantis/utilities/v2/)
#   AWS_RELEASE_BUCKET_TEMPLATES_PATH - Must be single / or begin and end with / (suggested: /atlantis/templates/)
#

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_RELEASE_ACCT }}:role/github-actions-role # Must be set up in the target account
          aws-region: ${{ secrets.AWS_RELEASE_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install AWS CLI
        run: |
          pip install --upgrade awscli boto3

      - name: Sync templates
        run: |
          chmod +x ./scripts/sync_templates.sh
          ./scripts/sync_templates.sh templates ${{ vars.AWS_RELEASE_BUCKET }} ${{ vars.AWS_RELEASE_BUCKET_TEMPLATES_PATH }}

      - name: Upload utility scripts
        run: |
          chmod +x ./scripts/upload_scripts.sh
          ./scripts/upload_scripts.sh ${{ vars.AWS_RELEASE_BUCKET }}${{ vars.AWS_RELEASE_BUCKET_UTILS_PATH }} scripts
